version: '3.5'

services:
  samba:
    build: .
    image: alpine-samba:3.11

    container_name: "samba"
    ports:
      - "445:445"
    volumes:
     - ./config/:/etc/samba/
     - /your/samba/path1:/share/user1
     - /your/samba/path2:/share/user_folder2
    restart: always

networks:
  default:
    name: samba
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/30