version: '2'

services:
  samba:
    build:
      context: .

    container_name: "samba"
    ports:
      - "445:445"
    volumes:
     - ./config/:/etc/samba/
     - /your/samba/path1:/share/user1
     - /your/samba/path2:/share/user_folder2
    restart: always
