FROM node:18-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
  && apk add --no-cache tzdata \
  && npm config set registry https://registry.npmmirror.com \
  && npm install -g pnpm 

ENV TZ=Asia/Shanghai