FROM node:20-alpine

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
  && apk add --no-cache tzdata font-wqy-zenhei udev chromium \
  && npm config set registry https://registry.npmmirror.com 

ENV TZ=Asia/Shanghai