
FROM python:3.12


RUN sed -i "s@http://deb.debian.org@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list.d/debian.sources \
  && apt-get update && apt-get install -y libgl1 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Shanghai